INSERT INTO ACCOUNT (ID,BALANCE, CURRENCY, CREATED_AT,VERSION) VALUES (101,'1000', 'GBP',SYSDATE,0);
INSERT INTO ACCOUNT (ID,BALANCE, CURRENCY, CREATED_AT,VERSION) VALUES (102,'2000', 'GBP',SYSDATE,0);
INSERT INTO ACCOUNT (ID,BALANCE, CURRENCY, CREATED_AT,VERSION) VALUES (103,'2000', 'USD',SYSDATE,0);